import {Database} from "./database/types.js";

type ItemType = Database['public']['Enums']['item_type'] // 'business' | 'resource' | 'event'

export type Seed = {
    typeName: string
    item_type: ItemType
    cross_category?: boolean
    tags: { name: string; cross_category?: boolean }[]
}

export const EVENT_SEED_TYPES_TAGS: Seed[] = [
    {
        typeName: 'Pride & Seasonal',
        item_type: 'event',
        tags: [
            { name: 'Pride Parades & Festivals', cross_category: false },
            { name: 'Queer Holiday Events', cross_category: false },
            { name: 'Coming Out Day Celebrations', cross_category: false },
            { name: 'Queer Prom & Costume Parties', cross_category: false },
            { name: 'Youth Prom', cross_category: false },
            { name: 'Elder Prom', cross_category: false },
            { name: 'Pride March', cross_category: false },
            { name: 'Pride Rally', cross_category: false },
            { name: 'Pride Block Party', cross_category: false },
            { name: 'Pride Boat Cruise', cross_category: false },
            { name: 'Pride History', cross_category: false },
            { name: 'Flag Raising', cross_category: false },
            { name: 'World Pride', cross_category: false },
            { name: 'Pride Kick Off', cross_category: false },
            { name: 'Official Pride Party', cross_category: false },
            { name: 'Pride Festival Packages', cross_category: false },
        ],
    },
    {
        typeName: 'Identity-Specific Spaces',
        item_type: 'event',
        tags: [
            { name: '2SLGBTQIA+', cross_category: false },
            { name: 'Queer-Affirming Spaces', cross_category: false },
            { name: 'Trans & Nonbinary', cross_category: false },
            { name: 'Lesbian, Bi, & WLW', cross_category: false },
            { name: 'Gay, Bi, & MLM', cross_category: false },
            { name: 'Asexual & Aromantic Gatherings', cross_category: false },
            { name: 'Two-Spirit & Indigenous Spaces', cross_category: false },
        ],
    },
    {
        typeName: 'Socials & Nightlife',
        item_type: 'event',
        tags: [
            { name: 'Club Nights & Dance Parties', cross_category: false },
            { name: 'Queer Bars & Theme Nights', cross_category: false },
            { name: 'Drag Brunch & Tea Parties', cross_category: false },
            { name: 'Leather & Kink Events', cross_category: false },
            { name: 'Pride After Parties & After-Hours', cross_category: false },
            { name: 'Sober & Low-Sensory Events', cross_category: false },
            { name: 'Open Mics, Trivia & Karaoke', cross_category: false },
            { name: 'Queer DJ Sets & Raves', cross_category: false },
            { name: 'Fetish & Underground Events', cross_category: false },
            { name: 'Pop Up Events', cross_category: false },
            { name: 'Clothing Swap / Drive', cross_category: false },
            { name: 'Drag/Bingo', cross_category: false },
        ],
    },
    {
        typeName: 'Arts, Music & Performance',
        item_type: 'event',
        tags: [
            { name: 'Queer Live Music', cross_category: false },
            { name: 'Spoken Word & Poetry Slams', cross_category: false },
            { name: 'Drag Shows & Cabarets', cross_category: false },
            { name: 'Queer Film Screenings & Festivals', cross_category: false },
            { name: 'Gallery Openings & Art Shows', cross_category: false },
            { name: 'Book Readings', cross_category: false },
            { name: 'Arts & Crafts Events', cross_category: false },
            { name: "Q&A’s + Discussions", cross_category: false },
        ],
    },
    {
        typeName: 'Community & Culture',
        item_type: 'event',
        tags: [
            { name: 'Meetups & Mixers', cross_category: false },
            { name: 'Drag & Ballroom Events', cross_category: false },
            { name: '2SLGBTQIA+ History & Heritage', cross_category: false },
            { name: 'Intergenerational Gatherings', cross_category: false },
            { name: 'QTPOC Events', cross_category: false },
            { name: 'Fundraisers & Galas', cross_category: false },
        ],
    },
    {
        typeName: 'Friends & Family',
        item_type: 'event',
        tags: [
            { name: 'Family Acceptance Workshops', cross_category: false },
            { name: 'PFLAG Meetings', cross_category: false },
            { name: 'Queer 101 for Families', cross_category: false },
            { name: 'Community Dinners / Potlucks', cross_category: false },
            { name: 'Ally Training Sessions', cross_category: false },
            { name: 'Support Circles for Parents/Guardians', cross_category: false },
        ],
    },
    {
        typeName: 'Health & Wellness',
        item_type: 'event',
        tags: [
            { name: 'Mental Health Circles', cross_category: false },
            { name: 'Peer Support Groups', cross_category: false },
            { name: 'Sexual Health Clinics & Info Sessions', cross_category: false },
            { name: 'Yoga, Meditation & Movement', cross_category: false },
            { name: 'Harm Reduction & Recovery Spaces', cross_category: false },
        ],
    },
    {
        typeName: 'Resources & Services',
        item_type: 'event',
        tags: [
            { name: 'Free Testing & Health Clinics', cross_category: false },
            { name: 'Legal Aid & Name Change Clinics', cross_category: false },
            { name: 'Mutual Aid Drives', cross_category: false },
            { name: 'Housing & Shelter Access', cross_category: false },
            { name: 'Therapy & Counseling Resources', cross_category: false },
        ],
    },
    {
        typeName: 'Education & Workshops',
        item_type: 'event',
        tags: [
            { name: 'Gender & Sexuality Workshops', cross_category: false },
            { name: 'Sex Ed & Body Positivity', cross_category: false },
            { name: 'Writing, Art & Creative Labs', cross_category: false },
            { name: 'Legal Rights & Advocacy', cross_category: false },
            { name: 'Financial Literacy', cross_category: false },
        ],
    },
    {
        typeName: 'Religion & Spirituality',
        item_type: 'event',
        tags: [
            { name: 'Queer-Affirming Worship Services', cross_category: false },
            { name: '2SLGBTQIA+ Interfaith Gatherings', cross_category: false },
            { name: 'Trans & Queer Healing Circles', cross_category: false },
            { name: 'Religious Trauma Support Groups', cross_category: false },
            { name: 'Pride Shabbat, Queer Seder, Queer Eid', cross_category: false },
            { name: 'Faith-Based Ally Trainings', cross_category: false },
            { name: '2SLGBTQIA+ Faith & Justice Panels', cross_category: false },
            { name: 'Meditation, Prayer & Reflection Spaces', cross_category: false },
            { name: 'Queer Clergy-Led Ceremonies', cross_category: false },
            { name: 'Inclusive Faith Community Events', cross_category: false },
        ],
    },
    {
        typeName: 'Business & Career',
        item_type: 'event',
        tags: [
            { name: 'Queer-Owned Business Markets', cross_category: false },
            { name: '2SLGBTQIA+ Professional Networking', cross_category: false },
            { name: 'Job Fairs & Hiring Events', cross_category: false },
            { name: 'Pitch Nights & Start-Up Showcases', cross_category: false },
            { name: 'Vendor & Volunteer Registration', cross_category: false },
            { name: 'DEI Trainings & Panels', cross_category: false }
        ],
    },
    {
        typeName: 'Sports & Recreation',
        item_type: 'event',
        tags: [
            { name: 'Queer Sports Tournaments', cross_category: false },
            { name: '2SLGBTQIA+ Rec Leagues', cross_category: false },
            { name: 'Pride Runs, Walks & Races', cross_category: false },
            { name: 'Open Gym & Pickup Games', cross_category: false },
            { name: 'Queer Hikes & Outdoor Adventures', cross_category: false },
            { name: 'Inclusive Fitness Classes', cross_category: false },
            { name: 'Roller Skating Nights', cross_category: false },
            { name: 'Queer Bike Rides', cross_category: false },
            { name: 'Pool Parties & Swim Meets', cross_category: false },
            { name: 'Trans-Inclusive Athletics', cross_category: false },
        ],
    },
]

export const EVENT_CROSS_CATEGORY_SEED: Seed[] = [
    {
        typeName: 'Age',
        item_type: 'event',
        cross_category: true,
        tags: [
            { name: 'Youth / 14+', cross_category: true },
            { name: 'Teen / 16+', cross_category: true },
            { name: 'Adult / 18+', cross_category: true },
            { name: 'Adult / 19+', cross_category: true },
            { name: 'Adult / 21+', cross_category: true },
            { name: 'All Ages', cross_category: true },
            { name: 'Disability-Inclusive', cross_category: true },
            { name: 'BIPOC-Led', cross_category: true },
            { name: 'Immigrant-Led', cross_category: true },
            { name: 'Queer-Owned', cross_category: true },
            { name: 'Sober & Recovery-Friendly', cross_category: true },
            { name: 'Low-Sensory / Accessible', cross_category: true },
        ],
    },
    {
        typeName: 'Identity / Ownership',
        item_type: 'event',
        cross_category: true,
        tags: [
            { name: 'Disability-Inclusive', cross_category: true },
            { name: 'BIPOC-Led', cross_category: true },
            { name: 'Immigrant-Led', cross_category: true },
            { name: 'Queer-Owned', cross_category: true },
        ],
    },
    {
        typeName: 'Accessibility / Environment',
        item_type: 'event',
        cross_category: true,
        tags: [
            { name: 'Sober & Recovery-Friendly', cross_category: true },
            { name: 'Low-Sensory / Accessible', cross_category: true },
        ],
    },
]


export const BUSINESS_SEED_TYPES_AND_TAGS: Seed[] = [
    {
        typeName: 'Arts & Culture',
        item_type: 'business',
        tags: [
            { name: 'Artist Studios & Open-Work Spaces', cross_category: false },
            { name: 'Cultural Festivals', cross_category: false },
            { name: 'Fringe & Experimental Arts Spaces', cross_category: false },
            { name: 'Local Art Fairs & Gallery Districts', cross_category: false },
            { name: 'Performing Arts Venues', cross_category: false },
            { name: 'Queer Craft Zine & Comic Creators', cross_category: false },
            { name: 'Queer Film & Independent Cinemas', cross_category: false },
            { name: 'Queer Literary Spaces & Poetry Venues', cross_category: false },
            { name: 'Queer Playwrights Actors & Ensembles', cross_category: false },
            { name: 'Musicians, Dancers & Visual Artists/ Performers', cross_category: false },
        ],
    },
    {
        typeName: 'Attractions & Activities',
        item_type: 'business',
        tags: [
            { name: 'Architectural Sites & City Icons', cross_category: false },
            { name: 'Botanical Gardens & Conservatories', cross_category: false },
            { name: 'Community Cultural Centers', cross_category: false },
            { name: 'Interactive Science & Discovery Centers', cross_category: false },
            { name: 'LGBTQ+ Heritage Walks & Monuments', cross_category: false },
            { name: 'Museums', cross_category: false },
            { name: 'Murals & Queer Street Art', cross_category: false },
            { name: 'Observatories & Planetariums', cross_category: false },
            { name: 'Public Art Installations & Sculptures', cross_category: false },
            { name: 'Queer Landmarks & Historic Sites', cross_category: false },
            { name: 'Zoos & Aquariums', cross_category: false },
        ],
    },
    {
        typeName: 'Community Nonprofit & Public Services',
        item_type: 'business',
        tags: [
            { name: 'Queer Community Events/Venues', cross_category: false },
            { name: 'Cultural Offices', cross_category: false },
            { name: 'Legal Aid & LGBTQ+ Rights Firms (For-Profit)', cross_category: false },
            { name: 'Local Government LGBTQ+ Liaisons (Third-Party)', cross_category: false },
            { name: 'Mediation & Conflict Resolution Services', cross_category: false },
            { name: 'Private Security & Community Safety Firms', cross_category: false },
            { name: 'Professional Training & Certification Providers', cross_category: false },
            { name: 'Tourism Boards (Private / For-Profit Tourism Offices)', cross_category: false },
        ],
    },
    {
        typeName: 'Family, Kids & Education',
        item_type: 'business',
        tags: [
            { name: 'Family Resource Centers', cross_category: false },
            { name: 'Family-Friendly Cafés & Bakeries', cross_category: false },
            { name: 'Inclusive Clothing & Gift Boutiques', cross_category: false },
            { name: 'Kid-Inclusive Fitness & Recreation Studios', cross_category: false },
            { name: 'LGBTQ+ Event Planners', cross_category: false },
            { name: 'LGBTQ+ Family Photographers', cross_category: false },
            { name: 'LGBTQ+ Parenting Programs', cross_category: false },
            { name: 'Queer-Friendly Arcades Mini Golf & Play Spaces', cross_category: false },
            { name: 'Queer-Owned Childcare & Babysitting', cross_category: false },
            { name: 'Queer-Owned Toy & Book Shops', cross_category: false },
            { name: 'Tutoring Centers & Educational Supply Shops', cross_category: false },
            { name: 'Youth Arts & Creative Workshops', cross_category: false },
        ],
    },
    {
        typeName: 'Food & Drink',
        item_type: 'business',
        tags: [
            { name: 'Bakeries & Dessert Shops', cross_category: false },
            { name: 'Breweries Pubs & Lounges', cross_category: false },
            { name: 'Cocktail Bars & Lounges', cross_category: false },
            { name: 'Food Co-ops & Community Kitchens', cross_category: false },
            { name: 'Food Trucks & Pop-Ups', cross_category: false },
            { name: 'Queer Cafés & Coffeehouses', cross_category: false },
            { name: 'Queer Caterers & Private Chefs', cross_category: false },
            { name: 'Queer-Owned / Grocery & Market Stalls', cross_category: false },
            { name: 'Queer-Owned / Restaurants & Diners', cross_category: false },
            { name: 'Specialty Food Shops', cross_category: false },
            { name: 'Vegan & Vegetarian Spots', cross_category: false },
            { name: 'Wine Bars & Tasting Rooms', cross_category: false },
            { name: 'Clubs & Clubhouses', cross_category: false },
        ],
    },
    {
        typeName: 'Health, Beauty & Wellness',
        item_type: 'business',
        tags: [
            { name: 'Barbershops & Grooming Studios', cross_category: false },
            { name: 'Holistic & Alternative Medicine', cross_category: false },
            { name: 'LGBTQ+ Health Clinics & Practices', cross_category: false },
            { name: 'Massage & Bodywork Practices', cross_category: false },
            { name: 'Meditation & Mindfulness Centers', cross_category: false },
            { name: 'Mental Health Providers', cross_category: false },
            { name: 'Queer-Affirming / Spas & Salons', cross_category: false },
            { name: 'Queer-Friendly Gyms', cross_category: false },
            { name: 'Sexual Health & Wellness Clinics', cross_category: false },
            { name: 'Tattoo & Piercing Studios', cross_category: false },
            { name: 'Voice Coaching & Gender-Affirming Services', cross_category: false },
            { name: 'Yoga Dance & Fitness Studios', cross_category: false },
        ],
    },
    {
        typeName: 'Home & Lifestyle Services',
        item_type: 'business',
        tags: [
            { name: 'Cleaning Services', cross_category: false },
            { name: 'Gardening & Landscaping', cross_category: false },
            { name: 'Home Décor & Furniture Shops', cross_category: false },
            { name: 'Movers & Hauling Services', cross_category: false },
            { name: 'Real Estate Agents & Queer-Affirming Realtors', cross_category: false },
            { name: 'Repair Services', cross_category: false },
        ],
    },
    {
        typeName: 'Nightlife & Entertainment',
        item_type: 'business',
        tags: [
            { name: 'Dance Clubs & Queer Nights', cross_category: false },
            { name: 'Drag & Cabaret Performances / Venues', cross_category: false },
            { name: 'Tea Dances & Pageants', cross_category: false },
            { name: 'Boat & Cruise Parties', cross_category: false },
            { name: 'Fetish Leather & Underground Events', cross_category: false },
            { name: 'Immersive Queer Events & Alt Spaces', cross_category: false },
            { name: 'Indie Theaters & Performance Spaces', cross_category: false },
            { name: 'Karaoke Trivia & Game Nights', cross_category: false },
            { name: 'Live Music Venues', cross_category: false },
            { name: 'Pride & Festival Party Venues', cross_category: false },
            { name: 'Queer / Bars & Taverns', cross_category: false },
            { name: 'Queer / Comedy Shows & Open Mics', cross_category: false },
            { name: 'Queer / DJ Sets & Raves', cross_category: false },
            { name: 'Sober & Low-Sensory Nightlife', cross_category: false },
        ],
    },
    {
        typeName: 'Outdoor & Recreation',
        item_type: 'business',
        tags: [
            { name: 'Bike Paths & Cycling Routes', cross_category: false },
            { name: 'Dog Parks & Pet-Friendly Spaces', cross_category: false },
            { name: 'LGBTQ+ Camping & Outdoor Retreat Sites', cross_category: false },
            { name: 'Nature Reserves & Wildlife Areas', cross_category: false },
            { name: 'Parks & Green Spaces', cross_category: false },
            { name: 'Public Pools & Recreation Centers', cross_category: false },
            { name: 'Queer-Friendly Outdoor Adventure Groups', cross_category: false },
            { name: 'Trailheads & Hiking Routes', cross_category: false },
            { name: 'Waterfronts Beaches & Piers', cross_category: false },
            { name: 'Boat Tours & Cruises', cross_category: false },
            { name: 'Walks, Runs & Marathons', cross_category: false },
        ],
    },
    {
        typeName: 'Professional & Creative Services',
        item_type: 'business',
        tags: [
            { name: 'Networking & Mentorship', cross_category: false },
            { name: 'Financial Services', cross_category: false },
            { name: 'Co-Working & Office Spaces', cross_category: false },
            { name: 'Design Studios', cross_category: false },
            { name: 'Film Stage & Event Production', cross_category: false },
            { name: 'HR DEI & Organizational Consulting', cross_category: false },
            { name: 'Legal & Accounting Services', cross_category: false },
            { name: 'Marketing Branding & PR Agencies', cross_category: false },
            { name: 'Photography Videography & Creative Studios', cross_category: false },
            { name: 'Print & Production Shops', cross_category: false },
            { name: 'Queer-Owned Businesses', cross_category: false },
            { name: 'Web Development & Tech Firms', cross_category: false },
        ],
    },
    {
        typeName: 'Retail & Shopping',
        item_type: 'business',
        tags: [
            { name: 'Adult Intimacy & Toy Shops', cross_category: false },
            { name: 'Art Galleries & Queer Artist Collectives', cross_category: false },
            { name: 'Craft Supply & Stationery Stores', cross_category: false },
            { name: 'Fashion Boutiques & Apparel Shops', cross_category: false },
            { name: 'Home Goods & Décor Shops', cross_category: false },
            { name: 'Jewelry & Accessories Shops', cross_category: false },
            { name: 'Makers Markets & Pop-Up Shops', cross_category: false },
            { name: 'Plant Shops & LGBTQ+ Florists', cross_category: false },
            { name: 'Queer-Owned Bookstores', cross_category: false },
            { name: 'Record & Music Shops', cross_category: false },
            { name: 'Specialty Retail', cross_category: false },
            { name: 'Thrift Vintage & Consignment Stores', cross_category: false },
        ],
    },
    {
        typeName: 'Travel, Tourism & Lodging',
        item_type: 'business',
        tags: [
            { name: 'Accessible Transport Providers', cross_category: false },
            { name: 'Airport Transfers & Rideshare Alternatives', cross_category: false },
            { name: 'B&Bs & Guesthouses', cross_category: false },
            { name: 'Bike Rentals Scooters & Micro-Mobility', cross_category: false },
            { name: 'Boutique & Luxury Stays', cross_category: false },
            { name: 'LGBTQ+ Campgrounds & Cabins', cross_category: false },
            { name: 'LGBTQ+ Shuttle Services', cross_category: false },
            { name: 'LGBTQ+ Tour Operators', cross_category: false },
            { name: 'LGBTQ+ Travel Media', cross_category: false },
            { name: 'Queer City Guides & Local Hosts', cross_category: false },
            { name: 'Queer-Owned / Hotels & Hostels', cross_category: false },
            { name: 'Queer-Owned Transportation', cross_category: false },
            { name: 'Pride & Festival Travel Packages', cross_category: false },
            { name: 'Short-Term Rentals', cross_category: false },
            { name: 'Visitor Centers & Tourism Boards', cross_category: false }
        ],
    },
]

export const BUSINESS_CROSS_CATEGORY_SEED: Seed[] = [
    {
        typeName: 'Age',
        item_type: 'business',
        cross_category: true,
        tags: [
            { name: 'Youth 14+', cross_category: true },
            { name: 'Teen 16+', cross_category: true },
            { name: 'Adult 18+', cross_category: true },
            { name: 'Adult 19+', cross_category: true },
            { name: 'Adult 21+', cross_category: true },
            { name: 'Intergenerational', cross_category: true },
        ],
    },
    {
        typeName: 'Identity / Ownership',
        item_type: 'business',
        cross_category: true,
        tags: [
            { name: 'BIPOC-Led', cross_category: true },
            { name: 'Immigrant-Led', cross_category: true },
            { name: 'Trans-Led', cross_category: true },
            { name: 'Nonbinary-Led', cross_category: true },
            { name: 'Intersex-Led', cross_category: true },
            { name: 'Two-Spirit-Led', cross_category: true },
            { name: 'Women-Led', cross_category: true },
            { name: 'Seniors 50+ Owned', cross_category: true },
            { name: 'Queer-Owned', cross_category: true },
            { name: 'Ally-Owned', cross_category: true },
        ],
    },
    {
        typeName: 'Accessibility / Environment',
        item_type: 'business',
        cross_category: true,
        tags: [
            { name: 'Disability-Inclusive', cross_category: true },
            { name: 'Low-Sensory / Accessible', cross_category: true },
            { name: 'Sober & Recovery-Friendly', cross_category: true },
        ],
    },
    {
        typeName: 'Business Style / Operations',
        item_type: 'business',
        cross_category: true,
        tags: [
            { name: 'Outdoor / Seasonal', cross_category: true },
            { name: 'Mobile / Pop-Up', cross_category: true },
            { name: 'Eco-Friendly / Sustainable', cross_category: true },
            { name: 'Heritage / Historical', cross_category: true },
            { name: 'Fair Trade / Ethical', cross_category: true },
        ],
    },
]



export const RESOURCE_SEED_TYPES_AND_TAGS: Seed[] = [
    {
        typeName: 'Community & Advocacy',
        item_type: 'resource',
        tags: [
            { name: 'LGBTQ+ Community Centers', cross_category: false },
            { name: 'Pride & Advocacy Organizations', cross_category: false },
            { name: 'Youth & Student Programs', cross_category: false },
            { name: 'Senior & Elder Queer Programs', cross_category: false },
            { name: 'QTPOC Collectives', cross_category: false },
            { name: 'Trans & Nonbinary Networks', cross_category: false },
            { name: 'Lesbian / WLW Groups', cross_category: false },
            { name: 'Gay / MLM Groups', cross_category: false },
            { name: '2-Spirit & Indigenous Spaces', cross_category: false },
            { name: 'Immigrant & Refugee Queer Support', cross_category: false },
        ],
    },
    {
        typeName: 'Health & Wellness',
        item_type: 'resource',
        tags: [
            { name: 'Mental Health Counseling & Therapy', cross_category: false },
            { name: 'Peer Support Groups', cross_category: false },
            { name: 'HIV Testing & PrEP Access', cross_category: false },
            { name: 'STI Clinics & Sexual Health Services', cross_category: false },
            { name: 'Gender-Affirming Care (HRT, Surgery, Voice, Hair Removal)', cross_category: false },
            { name: 'Recovery & Harm Reduction Programs', cross_category: false },
            { name: 'Disability-Inclusive Wellness', cross_category: false },
            { name: 'Accessible Fitness & Recreation', cross_category: false },
        ],
    },
    {
        typeName: 'Legal & Rights Support',
        item_type: 'resource',
        tags: [
            { name: 'Legal Aid Clinics', cross_category: false },
            { name: 'Name & ID Change Support', cross_category: false },
            { name: 'Housing Rights & Tenant Advocacy', cross_category: false },
            { name: 'Workplace Rights & Union Allies', cross_category: false },
            { name: 'Immigration & Asylum Legal Support', cross_category: false },
            { name: 'Anti-Discrimination & Civil Rights Services', cross_category: false },
        ],
    },
    {
        typeName: 'Education & Learning',
        item_type: 'resource',
        tags: [
            { name: 'Queer Libraries & Archives', cross_category: false },
            { name: 'Queer History & Heritage Projects', cross_category: false },
            { name: 'Workshops & Trainings (DEI, Allyship, Queer 101)', cross_category: false },
            { name: 'Sex Ed & Body Positivity Programs', cross_category: false },
            { name: 'University LGBTQ+ Groups', cross_category: false },
            { name: 'Queer Art & Writing Labs', cross_category: false },
            { name: 'Financial Literacy Workshops', cross_category: false },
        ],
    },
    {
        typeName: 'Crisis & Safety Support',
        item_type: 'resource',
        tags: [
            { name: 'Crisis Hotlines', cross_category: false },
            { name: 'Suicide Prevention Services', cross_category: false },
            { name: 'Domestic Violence Shelters', cross_category: false },
            { name: 'Homeless Queer Youth Programs', cross_category: false },
            { name: 'Family & Parent Acceptance Support', cross_category: false },
            { name: 'Emergency Housing & Shelter Access', cross_category: false },
        ],
    },
    {
        typeName: 'Faith & Spirituality',
        item_type: 'resource',
        tags: [
            { name: 'Queer-Affirming Churches', cross_category: false },
            { name: 'Inclusive Synagogues, Mosques & Temples', cross_category: false },
            { name: 'Interfaith Queer Gatherings', cross_category: false },
            { name: 'Religious Trauma Support', cross_category: false },
            { name: 'Queer Ritual & Spiritual Circles', cross_category: false },
            { name: 'Queer Clergy & Officiants', cross_category: false },
        ],
    },
    {
        typeName: 'Social & Community Events',
        item_type: 'resource',
        tags: [
            { name: 'Queer Sports Leagues & Recreation', cross_category: false },
            { name: 'Outdoor & Adventure Groups', cross_category: false },
            { name: 'Arts & Maker Collectives', cross_category: false },
            { name: 'Book Clubs & Reading Groups', cross_category: false },
            { name: 'Intergenerational Gatherings', cross_category: false },
            { name: 'Social Meetups & Interest Groups', cross_category: false },
        ],
    },
    {
        typeName: 'Practical Help & Services',
        item_type: 'resource',
        tags: [
            { name: 'Food Pantries & Mutual Aid', cross_category: false },
            { name: 'Housing Support Services', cross_category: false },
            { name: 'Job Training & Career Navigation', cross_category: false },
            { name: 'Queer Mentorship Programs', cross_category: false },
            { name: 'Technology Access & Digital Literacy', cross_category: false },
            { name: 'Trans & Nonbinary Resource Navigators', cross_category: false },
        ],
    },
]

export const RESOURCE_CROSS_CATEGORY_SEED: Seed[] = [
    {
        typeName: 'Age',
        item_type: 'resource',
        cross_category: true,
        tags: [
            { name: 'Youth 14+', cross_category: true },
            { name: 'Teen 16+', cross_category: true },
            { name: 'Adult 18+', cross_category: true },
            { name: 'Adult 19+', cross_category: true },
            { name: 'Adult 21+', cross_category: true },
            { name: 'Intergenerational', cross_category: true },
        ],
    },
    {
        typeName: 'Identity / Ownership',
        item_type: 'resource',
        cross_category: true,
        tags: [
            { name: 'BIPOC-Led', cross_category: true },
            { name: 'Immigrant-Led', cross_category: true },
            { name: 'Queer-Owned', cross_category: true },
        ],
    },
    {
        typeName: 'Accessibility / Environment',
        item_type: 'resource',
        cross_category: true,
        tags: [
            { name: 'Disability-Inclusive', cross_category: true },
            { name: 'Low-Sensory / Accessible', cross_category: true },
            { name: 'Sober & Recovery-Friendly', cross_category: true },
        ],
    },
]

