import { Database } from "./database/types.js";

type ItemType = Database['public']['Enums']['item_type'] // 'business' | 'resource' | 'event'

export type Seed = {
    typeName: string
    item_type: ItemType
    cross_category?: boolean
    tags: string[]
}

export const EVENT_SEED_TYPES_TAGS: Seed[] = [
    {
        typeName: 'Pride & Seasonal',
        item_type: 'event',
        tags: [
            'Pride Parades & Festivals',
            'Queer Holiday Events',
            'Coming Out Day Celebrations',
            'Queer Prom & Costume Parties',
            'Youth Prom',
            'Elder Prom',
            'Pride March',
            'Pride Rally',
            'Pride Block Party',
            'Pride Boat Cruise',
            'Pride History',
            'Flag Raising',
            'World Pride',
            'Pride Kick Off',
            'Official Pride Party',
            'Pride Festival Packages',
        ],
    },
    {
        typeName: 'Identity-Specific Spaces',
        item_type: 'event',
        tags: [
            '2SLGBTQIA+',
            'Queer-Affirming Spaces',
            'Trans & Nonbinary',
            'Lesbian, Bi, & WLW',
            'Gay, Bi, & MLM',
            'Asexual & Aromantic Gatherings',
            'Two-Spirit & Indigenous Spaces',
        ],
    },
    {
        typeName: 'Socials & Nightlife',
        item_type: 'event',
        tags: [
            'Club Nights & Dance Parties',
            'Queer Bars & Theme Nights',
            'Drag Brunch & Tea Parties',
            'Leather & Kink Events',
            'Pride After Parties & After-Hours',
            'Sober & Low-Sensory Events',
            'Open Mics, Trivia & Karaoke',
            'Queer DJ Sets & Raves',
            'Fetish & Underground Events',
            'Pop Up Events',
            'Clothing Swap / Drive',
            'Drag/Bingo',
        ],
    },
    {
        typeName: 'Arts, Music & Performance',
        item_type: 'event',
        tags: [
            'Queer Live Music',
            'Spoken Word & Poetry Slams',
            'Drag Shows & Cabarets',
            'Queer Film Screenings & Festivals',
            'Gallery Openings & Art Shows',
            'Book Readings',
            'Arts & Crafts Events',
            "Q&A’s + Discussions",
        ],
    },
    {
        typeName: 'Community & Culture',
        item_type: 'event',
        tags: [
            'Meetups & Mixers',
            'Drag & Ballroom Events',
            '2SLGBTQIA+ History & Heritage',
            'Intergenerational Gatherings',
            'QTPOC Events',
            'Fundraisers & Galas',
        ],
    },
    {
        typeName: 'Friends & Family',
        item_type: 'event',
        tags: [
            'Family Acceptance Workshops',
            'PFLAG Meetings',
            'Queer 101 for Families',
            'Community Dinners / Potlucks',
            'Ally Training Sessions',
            'Support Circles for Parents/Guardians',
        ],
    },
    {
        typeName: 'Health & Wellness',
        item_type: 'event',
        tags: [
            'Mental Health Circles',
            'Peer Support Groups',
            'Sexual Health Clinics & Info Sessions',
            'Yoga, Meditation & Movement',
            'Harm Reduction & Recovery Spaces',
        ],
    },
    {
        typeName: 'Resources & Services',
        item_type: 'event',
        tags: [
            'Free Testing & Health Clinics',
            'Legal Aid & Name Change Clinics',
            'Mutual Aid Drives',
            'Housing & Shelter Access',
            'Therapy & Counseling Resources',
        ],
    },
    {
        typeName: 'Education & Workshops',
        item_type: 'event',
        tags: [
            'Gender & Sexuality Workshops',
            'Sex Ed & Body Positivity',
            'Writing, Art & Creative Labs',
            'Legal Rights & Advocacy',
            'Financial Literacy',
        ],
    },
    {
        typeName: 'Religion & Spirituality',
        item_type: 'event',
        tags: [
            'Queer-Affirming Worship Services',
            '2SLGBTQIA+ Interfaith Gatherings',
            'Trans & Queer Healing Circles',
            'Religious Trauma Support Groups',
            'Pride Shabbat, Queer Seder, Queer Eid',
            'Faith-Based Ally Trainings',
            '2SLGBTQIA+ Faith & Justice Panels',
            'Meditation, Prayer & Reflection Spaces',
            'Queer Clergy-Led Ceremonies',
            'Inclusive Faith Community Events',
        ],
    },
    {
        typeName: 'Business & Career',
        item_type: 'event',
        tags: [
            'Queer-Owned Business Markets',
            '2SLGBTQIA+ Professional Networking',
            'Job Fairs & Hiring Events',
            'Pitch Nights & Start-Up Showcases',
            'Vendor & Volunteer Registration',
            'DEI Trainings & Panels',
        ],
    },
    {
        typeName: 'Sports & Recreation',
        item_type: 'event',
        tags: [
            'Queer Sports Tournaments',
            '2SLGBTQIA+ Rec Leagues',
            'Pride Runs, Walks & Races',
            'Open Gym & Pickup Games',
            'Queer Hikes & Outdoor Adventures',
            'Inclusive Fitness Classes',
            'Roller Skating Nights',
            'Queer Bike Rides',
            'Pool Parties & Swim Meets',
            'Trans-Inclusive Athletics',
        ],
    },
]

export const BUSINESS_SEED_TYPES_AND_TAGS: Seed[] = [
    {
        typeName: 'Arts & Culture',
        item_type: 'business',
        tags: [
            'Artist Studios & Open-Work Spaces',
            'Cultural Festivals',
            'Fringe & Experimental Arts Spaces',
            'Local Art Fairs & Gallery Districts',
            'Performing Arts Venues',
            'Queer Craft Zine & Comic Creators',
            'Queer Film & Independent Cinemas',
            'Queer Literary Spaces & Poetry Venues',
            'Queer Playwrights Actors & Ensembles',
            'Musicians, Dancers & Visual Artists/ Performers',
        ],
    },
    {
        typeName: 'Attractions & Activities',
        item_type: 'business',
        tags: [
            'Architectural Sites & City Icons',
            'Botanical Gardens & Conservatories',
            'Community Cultural Centers',
            'Interactive Science & Discovery Centers',
            'LGBTQ+ Heritage Walks & Monuments',
            'Museums',
            'Murals & Queer Street Art',
            'Observatories & Planetariums',
            'Public Art Installations & Sculptures',
            'Queer Landmarks & Historic Sites',
            'Zoos & Aquariums',
        ],
    },
    {
        typeName: 'Community Nonprofit & Public Services',
        item_type: 'business',
        tags: [
            'Queer Community Events/Venues',
            'Cultural Offices',
            'Legal Aid & LGBTQ+ Rights Firms (For-Profit)',
            'Local Government LGBTQ+ Liaisons (Third-Party)',
            'Mediation & Conflict Resolution Services',
            'Private Security & Community Safety Firms',
            'Professional Training & Certification Providers',
            'Tourism Boards (Private / For-Profit Tourism Offices)',
        ],
    },
    {
        typeName: 'Family, Kids & Education',
        item_type: 'business',
        tags: [
            'Family Resource Centers',
            'Family-Friendly Cafés & Bakeries',
            'Inclusive Clothing & Gift Boutiques',
            'Kid-Inclusive Fitness & Recreation Studios',
            'LGBTQ+ Event Planners',
            'LGBTQ+ Family Photographers',
            'LGBTQ+ Parenting Programs',
            'Queer-Friendly Arcades Mini Golf & Play Spaces',
            'Queer-Owned Childcare & Babysitting',
            'Queer-Owned Toy & Book Shops',
            'Tutoring Centers & Educational Supply Shops',
            'Youth Arts & Creative Workshops',
        ],
    },
    {
        typeName: 'Food & Drink',
        item_type: 'business',
        tags: [
            'Bakeries & Dessert Shops',
            'Breweries Pubs & Lounges',
            'Cocktail Bars & Lounges',
            'Food Co-ops & Community Kitchens',
            'Food Trucks & Pop-Ups',
            'Queer Cafés & Coffeehouses',
            'Queer Caterers & Private Chefs',
            'Queer-Owned / Grocery & Market Stalls',
            'Queer-Owned / Restaurants & Diners',
            'Specialty Food Shops',
            'Vegan & Vegetarian Spots',
            'Wine Bars & Tasting Rooms',
            'Clubs & Clubhouses',
        ],
    },
    {
        typeName: 'Health, Beauty & Wellness',
        item_type: 'business',
        tags: [
            'Barbershops & Grooming Studios',
            'Holistic & Alternative Medicine',
            'LGBTQ+ Health Clinics & Practices',
            'Massage & Bodywork Practices',
            'Meditation & Mindfulness Centers',
            'Mental Health Providers',
            'Queer-Affirming / Spas & Salons',
            'Queer-Friendly Gyms',
            'Sexual Health & Wellness Clinics',
            'Tattoo & Piercing Studios',
            'Voice Coaching & Gender-Affirming Services',
            'Yoga Dance & Fitness Studios',
        ],
    },
    {
        typeName: 'Home & Lifestyle Services',
        item_type: 'business',
        tags: [
            'Cleaning Services',
            'Gardening & Landscaping',
            'Home Décor & Furniture Shops',
            'Movers & Hauling Services',
            'Real Estate Agents & Queer-Affirming Realtors',
            'Repair Services',
        ],
    },
    {
        typeName: 'Nightlife & Entertainment',
        item_type: 'business',
        tags: [
            'Dance Clubs & Queer Nights',
            'Drag & Cabaret Performances / Venues',
            'Tea Dances & Pageants',
            'Boat & Cruise Parties',
            'Fetish Leather & Underground Events',
            'Immersive Queer Events & Alt Spaces',
            'Indie Theaters & Performance Spaces',
            'Karaoke Trivia & Game Nights',
            'Live Music Venues',
            'Pride & Festival Party Venues',
            'Queer / Bars & Taverns',
            'Queer / Comedy Shows & Open Mics',
            'Queer / DJ Sets & Raves',
            'Sober & Low-Sensory Nightlife',
        ],
    },
    {
        typeName: 'Outdoor & Recreation',
        item_type: 'business',
        tags: [
            'Bike Paths & Cycling Routes',
            'Dog Parks & Pet-Friendly Spaces',
            'LGBTQ+ Camping & Outdoor Retreat Sites',
            'Nature Reserves & Wildlife Areas',
            'Parks & Green Spaces',
            'Public Pools & Recreation Centers',
            'Queer-Friendly Outdoor Adventure Groups',
            'Trailheads & Hiking Routes',
            'Waterfronts Beaches & Piers',
            'Boat Tours & Cruises',
            'Walks, Runs & Marathons',
        ],
    },
    {
        typeName: 'Professional & Creative Services',
        item_type: 'business',
        tags: [
            'Networking & Mentorship',
            'Financial Services',
            'Co-Working & Office Spaces',
            'Design Studios',
            'Film Stage & Event Production',
            'HR DEI & Organizational Consulting',
            'Legal & Accounting Services',
            'Marketing Branding & PR Agencies',
            'Photography Videography & Creative Studios',
            'Print & Production Shops',
            'Queer-Owned Businesses',
            'Web Development & Tech Firms',
        ],
    },
    {
        typeName: 'Retail & Shopping',
        item_type: 'business',
        tags: [
            'Adult Intimacy & Toy Shops',
            'Art Galleries & Queer Artist Collectives',
            'Craft Supply & Stationery Stores',
            'Fashion Boutiques & Apparel Shops',
            'Home Goods & Décor Shops',
            'Jewelry & Accessories Shops',
            'Makers Markets & Pop-Up Shops',
            'Plant Shops & LGBTQ+ Florists',
            'Queer-Owned Bookstores',
            'Record & Music Shops',
            'Specialty Retail',
            'Thrift Vintage & Consignment Stores',
        ],
    },
    {
        typeName: 'Travel, Tourism & Lodging',
        item_type: 'business',
        tags: [
            'Accessible Transport Providers',
            'Airport Transfers & Rideshare Alternatives',
            'B&Bs & Guesthouses',
            'Bike Rentals Scooters & Micro-Mobility',
            'Boutique & Luxury Stays',
            'LGBTQ+ Campgrounds & Cabins',
            'LGBTQ+ Shuttle Services',
            'LGBTQ+ Tour Operators',
            'LGBTQ+ Travel Media',
            'Queer City Guides & Local Hosts',
            'Queer-Owned / Hotels & Hostels',
            'Queer-Owned Transportation',
            'Pride & Festival Travel Packages',
            'Short-Term Rentals',
            'Visitor Centers & Tourism Boards',
        ],
    },
]

export const RESOURCE_SEED_TYPES_AND_TAGS: Seed[] = [
    {
        typeName: 'Community & Advocacy',
        item_type: 'resource',
        tags: [
            'LGBTQ+ Community Centers',
            'Pride & Advocacy Organizations',
            'Youth & Student Programs',
            'Senior & Elder Queer Programs',
            'QTPOC Collectives',
            'Trans & Nonbinary Networks',
            'Lesbian / WLW Groups',
            'Gay / MLM Groups',
            '2-Spirit & Indigenous Spaces',
            'Immigrant & Refugee Queer Support',
        ],
    },
    {
        typeName: 'Health & Wellness',
        item_type: 'resource',
        tags: [
            'Mental Health Counseling & Therapy',
            'Peer Support Groups',
            'HIV Testing & PrEP Access',
            'STI Clinics & Sexual Health Services',
            'Gender-Affirming Care (HRT, Surgery, Voice, Hair Removal)',
            'Recovery & Harm Reduction Programs',
            'Disability-Inclusive Wellness',
            'Accessible Fitness & Recreation',
        ],
    },
    {
        typeName: 'Legal & Rights Support',
        item_type: 'resource',
        tags: [
            'Legal Aid Clinics',
            'Name & ID Change Support',
            'Housing Rights & Tenant Advocacy',
            'Workplace Rights & Union Allies',
            'Immigration & Asylum Legal Support',
            'Anti-Discrimination & Civil Rights Services',
        ],
    },
    {
        typeName: 'Education & Learning',
        item_type: 'resource',
        tags: [
            'Queer Libraries & Archives',
            'Queer History & Heritage Projects',
            'Workshops & Trainings (DEI, Allyship, Queer 101)',
            'Sex Ed & Body Positivity Programs',
            'University LGBTQ+ Groups',
            'Queer Art & Writing Labs',
            'Financial Literacy Workshops',
        ],
    },
    {
        typeName: 'Crisis & Safety Support',
        item_type: 'resource',
        tags: [
            'Crisis Hotlines',
            'Suicide Prevention Services',
            'Domestic Violence Shelters',
            'Homeless Queer Youth Programs',
            'Family & Parent Acceptance Support',
            'Emergency Housing & Shelter Access',
        ],
    },
    {
        typeName: 'Faith & Spirituality',
        item_type: 'resource',
        tags: [
            'Queer-Affirming Churches',
            'Inclusive Synagogues, Mosques & Temples',
            'Interfaith Queer Gatherings',
            'Religious Trauma Support',
            'Queer Ritual & Spiritual Circles',
            'Queer Clergy & Officiants',
        ],
    },
    {
        typeName: 'Social & Community Events',
        item_type: 'resource',
        tags: [
            'Queer Sports Leagues & Recreation',
            'Outdoor & Adventure Groups',
            'Arts & Maker Collectives',
            'Book Clubs & Reading Groups',
            'Intergenerational Gatherings',
            'Social Meetups & Interest Groups',
        ],
    },
    {
        typeName: 'Practical Help & Services',
        item_type: 'resource',
        tags: [
            'Food Pantries & Mutual Aid',
            'Housing Support Services',
            'Job Training & Career Navigation',
            'Queer Mentorship Programs',
            'Technology Access & Digital Literacy',
            'Trans & Nonbinary Resource Navigators',
        ],
    },
]
